!
!  LBM.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  1/19/2017 2:09:26 PM
!
    Module DataType
	implicit none
    integer, parameter ::RK=selected_real_kind(15,307)  ! Real Kind
        !-----------------------------
        !Distribution_information
        type DistroFunction
          Character (len=30) :: concept      
          Real(RK) :: delta_t
          Real(RK) :: tau
          Real(RK) :: C
          Real(RK) :: C2
          Real(RK) :: C4
          Real(RK) :: Cs2
        end type DistroFunction
        !-----------------------------  
        	type Wall_info
			integer::ctr=0
			Real(RK) :: Val1=0.0
			Real(RK) :: Val2=0.0
			Real(RK) :: Val3=0.0
		end type Wall_info
        !----------------------Type 3D
        !-----------------------------
        !Lattice_information
        type Latice_D3Q15
            integer:: Q=14
	        real (RK):: v_x(0:14)
            real (RK):: v_y(0:14)
            real (RK):: v_z(0:14)   
	        real (RK):: w_grid(0:14)          
	        integer:: inv_v(0:14)                      
        end type Latice_D3Q15
        !-----------------------------
    end module DataType